### ISSUE TITLE
Fields in ScheduleEvent

### ISSUE THREAD

**Issue by lixinze777** [CS2103-AY1819S1-T12-2/main#37]
In ScheduleEvent Class you have put in fields eventID, DateTime, personID, details and tag.  But I think it makes more sense to add in a field patient name.  In common sense, it would be more convenient if doctors know the name of a patient by looking at the schedule instead of only knowing his patient ID. Hence, may I add in a patient name field? @shuiherng

**Comment by shuiherng** [comment]
Since personID is technically a primary key which we can use to directly address any patient, we can technically load up the patient's name by calling `getPerson(PersonID)` when displaying. I'll find a way to put this method in if one of similar function does not already exist. In this way, on the front end, we will still have patient name available, but on the back end we reduce the amount of duplicate information stored. Do let know what you think of this :)
