### ISSUE TITLE
Request for Modification of getDiseases()

### ISSUE THREAD

**Issue by shuiherng** [CS2103-AY1819S1-T12-2/main#62]
Can we modify `DiagnosisModel.getDiseases()` to be a static method, since it is stateless. At the same time,  it should accept a `String[] symptomKeywords` as its argument and return a list of Strings representing the results that match the search terms, so it'll look something like:
```java
public static String[] getDiseases(String[] keywords) {
    ....
}
```

@ZZG229 for your consideration please. Also let me know if you prefer the entire search string to be passed in directly instead of an array of keywords.

**Comment by ZZG229** [comment]
1. I do not think we should change it to a static method because it depends on the private attribute matcher which is not a final attribute. i.e. I can add a disease and the private attribute will be updated so getDisease() will depend on the updated attribute
2. I thought it should accept a predicate instead of string
3. I have a class called Symptom so it may not be appropriate to return just a string[]

**Comment by shuiherng** [comment]
1. Acknowledged. Revised Definition: `public Symptom[] getDiseases(String keywords)`
2. But I'd be packaging it as a predicate and then you'd be unpacking it... I suppose we could do that if you wish, do let me know what's the predicate name so I can pack it into one to pass in.
3. Got it; changes are reflected in 1.
